[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "launch control"
authors = [{name = "Daniel Vesterbaek,", email = "daniel.v.jensen@gmail.com"}]
dynamic = ["version", "description"]
